### ISSUE TITLE
position of "poster" doesn't fit

### ISSUE THREAD

**Issue by Sennahoj82** [Tueti/MMM-MovieListings#1]
If I use the module with config option interface=poster, the picture is somewhere on the Screen.
No matter what position I set. Set I the position of the module top_right or top_left the text is behind the picture. Set I the position of the module bottom_right the text is not visible and the picture is every intervall on another position on the screen. Set I the position of the module bottom_left the picture is not visible.
What did I do wrong?

**Comment by Tueti** [comment]
Hi Sennahoj82,

do you have any custom CSS set for the mirror and what is your monitor's size?

**Comment by Sennahoj82** [comment]
Hi Tueti,

I have made some custom CSS setttings on the mirror. But this does not apply to your module. I'm actually  not at home. So I will post the Code when I'm back from work. My monitor: (24 Zoll) Full HD 1080p 16:9

Thanks for your help

**Comment by Tueti** [comment]
Okay, could you then also post your config.js? At least the part regarding this module? That would be great, thank you!

**Comment by Sennahoj82** [comment]
Hi.

Here is my config.js

`{
        		module: 'MMM-MovieListings',
        		position: 'bottom_right',
        		config: {
				header: 'Kinofilme',
            			region: 'DE',
            			apiKey: 'myAPI',
				interface: 'poster',
				moviesPerPage: '0', 
        			}
    		},`

and my custom CSS.

`body {
 }

.MMM-NetworkScanner .fa-ul{
	margin-left: 30px;
	margin-top: -5px;
}

.MMM-NetworkScanner .table {
    border-spacing: 0px 0px;
    border-collapse: separate;
}

.MMM-Fuel .table {
    border-spacing: 0px 0px;
    border-collapse: separate;
}

.newsfeed_de .fa{
	font-size: 15px;
}`

Thanks

**Comment by Sennahoj82** [comment]
This is what I mean.

position:bottom_right
![screenshot_bottom_right](https://cloud.githubusercontent.com/assets/26518669/24164077/dcc2ff8e-0e6c-11e7-8716-e0ee5e26803d.png)

position:top_right
![screenshot_top_right](https://cloud.githubusercontent.com/assets/26518669/24164097/ef09a0d0-0e6c-11e7-86d3-1e33205e1b24.png)

**Comment by Tueti** [comment]
I tried to reproduce the issue but wasn't able to manage it. With your exact configuration (I even added the CSS, even - as you said - they don't seem to apply to this module) the module works and displays fine on my mirror :-/ I even have the same layout (WunderGround and DWD top_right and the MovieListings bottom_right).

You seem to use most of the default values, could you try use this config:
```
{
   module: 'MMM-MovieListings',
   position: 'bottom_right',
   config: {
      apiKey: 'yourApiKey'
   }
},
```
Also, maybe you could check the logs. If it doesn't work with only these minimum config, we could try and go investigate those.

**Comment by Sennahoj82** [comment]
Hi Tueti.

I have solve the problem. It was my mistake. In my main.css there was a wrong setting. With the original main.css your module works perfectly. Sorry for the inconvenience and thanks for your help!

**Comment by Tueti** [comment]
Glad to hear that the problem is solved 👍
