### ISSUE TITLE
No wrapping on large textsblocks

### ISSUE THREAD

**Issue by Arkoxs** [Tueti/MMM-MovieListings#3]
If the movie description contains a lot of text, the text is stretching everything at that position.

**Comment by Kugelfang666** [comment]
I have the same problem!

**Comment by Tueti** [comment]
Sorry for the delay in giving a few infos about it. I read your issue just had been a busy time. I will fix it within the next few days (maybe even today). I will add a config value to decide if the plot is wanted and I will fix the text wrapping if you decide to display the plot

**Comment by Tueti** [comment]
Word wrap is now included. Also there is an option to disable showing the plot (it even defaults to not displaying it). If you want to keep it, please see the README for setting up the config
