### ISSUE TITLE
Nothing appears

### ISSUE THREAD

**Issue by ezar** [Tueti/MMM-MovieListings#5]
Hi,
Using this config:
                {
                        module: 'MMM-MovieListings',
                        position: 'top_left',
                        config: {
                                apiKey: '8dd97f779ddbf672b9c12330dccc30fc',
                                region: 'EN',
                                language: 'en-EN',
                                interface: 'list'
                        }
                },

Only appears KINOFILMS title...

**Comment by ezar** [comment]
Somobody?

**Comment by gmglickman** [comment]
Try region: 'US',

**Comment by ezar** [comment]
Yes! Using US region works. Can we use another regions?

**Comment by Tueti** [comment]
Hi,

Thank you @gmglickman for your assistance!

The movie info is fetched from [themoviedb.org](https://www.themoviedb.org/) and the API supports any official ISO 3166-1 region code. Please refer to [this wikipedia table](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Decoding_table) and see the green marked codes. Those should work.
