### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by ezar** [Tueti/MMM-MovieListings#6]
{
  "LOADING": "Cargando peliculas actuales...",
  "MIN": "min",
  "CAST": "Reparto",
  "DIRECTOR": "Director",
  "RATINGS": "clasificación",
  "GENRE": "Genero"
}

**Comment by Tueti** [comment]
Thank you! I will add that to the repo 👍

**Comment by Tueti** [comment]
Added with Commit 4cd9b9b
