### ISSUE TITLE
Cant make this work 

### ISSUE THREAD

**Issue by michael24h** [Tueti/MMM-MovieListings#7]
that my module in config, but won't load mirror. I'm getting error config file.
any help please

thanks
{
        module: 'MMM-MovieListings',
        

  		// Default module config.
		config: {
    	apiKey: "",
		region: 'EN',
    	language: 'en-EN',
    	interface: 'poster', //'list', 'poster', 'detailed'
    	includeMoviePlot: false,
    	maxPlotLength: 198,
    	header: 'Kinofilme',
    	moviesPerPage: 0,
    	refreshInterval: 1000 * 60 * 60 * 24, //Once a day
    	baseUrl: 'https://api.themoviedb.org/3/movie/550?
    	animationSpeed: 2.5 * 1000,
    	pageChangeInterval: 30 * 1000
		},

**Comment by Tueti** [comment]
Hi,
please look at [this issue](https://github.com/Tueti/MMM-MovieListings/issues/5). You can only use officially assigned ISO 3166-1 region codes. `EN` is not assigned. Please use `US` or `GB` instead.
