### ISSUE TITLE
Stuck on loading...

### ISSUE THREAD

**Issue by AndyC3108** [Tueti/MMM-MovieListings#8]
Hello

Sorry to bother you, but I am having an issue.
I have the module loading in Magic Mirror, but it is stuck on 'Loading'.
There do not appear to be any errors during startup.
All of my other modules are loading fine.
Do you have any suggestions?

Many thanks in advance...

AndyC

**Comment by Tueti** [comment]
Hi,
it's hard to tell without seeing your configuration. How did you set up the module in config.js?

**Comment by Tueti** [comment]
Hi again,
I will close the issue now as there hasn't been any feedback yet. If the issue still exists, please reach out again. I'm trying to help as best as I can.

Thank you!
