### ISSUE TITLE
Stuck at Loading...

### ISSUE THREAD

**Issue by fxlab7145** [Tueti/MMM-MovieListings#9]
Hi,
Working in MagicMirror2
with the following config.
{
                        module: "MMM-MovieListings",
                        position: "lower_third",
                        config: {
                                header: 'Movie Time',
                                apikey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                                region: 'US',
                                language: 'en-EN',
                                interface: 'poster',
                                refreshInterval: 30000,
                        }
                },

MagicMirror starts and so does the helper app, but it just show  "Loading...." and never loads.  Please advise.

Thanks,

**Comment by Tueti** [comment]
There's a typo in `apikey`, it's supposed to be `apiKey` - with a capital K. It should work with that as I tried with your settings and my apiKey
